package co.petsland.model;
// Generated 28/06/2015 09:53:51 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * EventosVeterinarias generated by hbm2java
 */
public class EventosVeterinarias  implements java.io.Serializable {


     private Long evCodigo;
     private Usuarios usuarios;
     private Veterinarias veterinarias;
     private String evMegusta;
     private Date evFechamg;
     private String evFavorito;
     private Date evFechaf;

    public EventosVeterinarias() {
    }

	
    public EventosVeterinarias(Long evCodigo, Usuarios usuarios, Veterinarias veterinarias) {
        this.evCodigo = evCodigo;
        this.usuarios = usuarios;
        this.veterinarias = veterinarias;
    }
    public EventosVeterinarias(Long evCodigo, Usuarios usuarios, Veterinarias veterinarias, String evMegusta, Date evFechamg, String evFavorito, Date evFechaf) {
       this.evCodigo = evCodigo;
       this.usuarios = usuarios;
       this.veterinarias = veterinarias;
       this.evMegusta = evMegusta;
       this.evFechamg = evFechamg;
       this.evFavorito = evFavorito;
       this.evFechaf = evFechaf;
    }
   
    public Long getEvCodigo() {
        return this.evCodigo;
    }
    
    public void setEvCodigo(Long evCodigo) {
        this.evCodigo = evCodigo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Veterinarias getVeterinarias() {
        return this.veterinarias;
    }
    
    public void setVeterinarias(Veterinarias veterinarias) {
        this.veterinarias = veterinarias;
    }
    public String getEvMegusta() {
        return this.evMegusta;
    }
    
    public void setEvMegusta(String evMegusta) {
        this.evMegusta = evMegusta;
    }
    public Date getEvFechamg() {
        return this.evFechamg;
    }
    
    public void setEvFechamg(Date evFechamg) {
        this.evFechamg = evFechamg;
    }
    public String getEvFavorito() {
        return this.evFavorito;
    }
    
    public void setEvFavorito(String evFavorito) {
        this.evFavorito = evFavorito;
    }
    public Date getEvFechaf() {
        return this.evFechaf;
    }
    
    public void setEvFechaf(Date evFechaf) {
        this.evFechaf = evFechaf;
    }




}


