package co.petsland.model;
// Generated 28/06/2015 09:53:51 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Long rolCodigo;
     private String rolNombre;
     private Date rolFechaCrea;
     private Date rolFechaModifica;
     private String rolUsuCrea;
     private String rolUsuModifica;
     private String rolEstado;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Roles() {
    }

	
    public Roles(Long rolCodigo, String rolNombre, Date rolFechaCrea, String rolUsuCrea, String rolEstado) {
        this.rolCodigo = rolCodigo;
        this.rolNombre = rolNombre;
        this.rolFechaCrea = rolFechaCrea;
        this.rolUsuCrea = rolUsuCrea;
        this.rolEstado = rolEstado;
    }
    public Roles(Long rolCodigo, String rolNombre, Date rolFechaCrea, Date rolFechaModifica, String rolUsuCrea, String rolUsuModifica, String rolEstado, Set<Usuarios> usuarioses) {
       this.rolCodigo = rolCodigo;
       this.rolNombre = rolNombre;
       this.rolFechaCrea = rolFechaCrea;
       this.rolFechaModifica = rolFechaModifica;
       this.rolUsuCrea = rolUsuCrea;
       this.rolUsuModifica = rolUsuModifica;
       this.rolEstado = rolEstado;
       this.usuarioses = usuarioses;
    }
   
    public Long getRolCodigo() {
        return this.rolCodigo;
    }
    
    public void setRolCodigo(Long rolCodigo) {
        this.rolCodigo = rolCodigo;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public Date getRolFechaCrea() {
        return this.rolFechaCrea;
    }
    
    public void setRolFechaCrea(Date rolFechaCrea) {
        this.rolFechaCrea = rolFechaCrea;
    }
    public Date getRolFechaModifica() {
        return this.rolFechaModifica;
    }
    
    public void setRolFechaModifica(Date rolFechaModifica) {
        this.rolFechaModifica = rolFechaModifica;
    }
    public String getRolUsuCrea() {
        return this.rolUsuCrea;
    }
    
    public void setRolUsuCrea(String rolUsuCrea) {
        this.rolUsuCrea = rolUsuCrea;
    }
    public String getRolUsuModifica() {
        return this.rolUsuModifica;
    }
    
    public void setRolUsuModifica(String rolUsuModifica) {
        this.rolUsuModifica = rolUsuModifica;
    }
    public String getRolEstado() {
        return this.rolEstado;
    }
    
    public void setRolEstado(String rolEstado) {
        this.rolEstado = rolEstado;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


