package co.petsland.model;
// Generated 28/06/2015 09:53:51 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private Long serCodigo;
     private String serNombre;
     private String serUsuCrea;
     private String serUsuModifica;
     private String serEstado;
     private Set<VetsServs> vetsServses = new HashSet<VetsServs>(0);

    public Servicios() {
    }

	
    public Servicios(Long serCodigo, String serNombre, String serUsuCrea, String serEstado) {
        this.serCodigo = serCodigo;
        this.serNombre = serNombre;
        this.serUsuCrea = serUsuCrea;
        this.serEstado = serEstado;
    }
    public Servicios(Long serCodigo, String serNombre, String serUsuCrea, String serUsuModifica, String serEstado, Set<VetsServs> vetsServses) {
       this.serCodigo = serCodigo;
       this.serNombre = serNombre;
       this.serUsuCrea = serUsuCrea;
       this.serUsuModifica = serUsuModifica;
       this.serEstado = serEstado;
       this.vetsServses = vetsServses;
    }
   
    public Long getSerCodigo() {
        return this.serCodigo;
    }
    
    public void setSerCodigo(Long serCodigo) {
        this.serCodigo = serCodigo;
    }
    public String getSerNombre() {
        return this.serNombre;
    }
    
    public void setSerNombre(String serNombre) {
        this.serNombre = serNombre;
    }
    public String getSerUsuCrea() {
        return this.serUsuCrea;
    }
    
    public void setSerUsuCrea(String serUsuCrea) {
        this.serUsuCrea = serUsuCrea;
    }
    public String getSerUsuModifica() {
        return this.serUsuModifica;
    }
    
    public void setSerUsuModifica(String serUsuModifica) {
        this.serUsuModifica = serUsuModifica;
    }
    public String getSerEstado() {
        return this.serEstado;
    }
    
    public void setSerEstado(String serEstado) {
        this.serEstado = serEstado;
    }
    public Set<VetsServs> getVetsServses() {
        return this.vetsServses;
    }
    
    public void setVetsServses(Set<VetsServs> vetsServses) {
        this.vetsServses = vetsServses;
    }




}


