package co.petsland.model;
// Generated 28/06/2015 09:53:51 PM by Hibernate Tools 4.0.0



/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private Long sucCodigo;
     private Veterinarias veterinarias;
     private String sucDireccion;
     private String sucTelefono;

    public Sucursales() {
    }

    public Sucursales(Long sucCodigo, Veterinarias veterinarias, String sucDireccion, String sucTelefono) {
       this.sucCodigo = sucCodigo;
       this.veterinarias = veterinarias;
       this.sucDireccion = sucDireccion;
       this.sucTelefono = sucTelefono;
    }
   
    public Long getSucCodigo() {
        return this.sucCodigo;
    }
    
    public void setSucCodigo(Long sucCodigo) {
        this.sucCodigo = sucCodigo;
    }
    public Veterinarias getVeterinarias() {
        return this.veterinarias;
    }
    
    public void setVeterinarias(Veterinarias veterinarias) {
        this.veterinarias = veterinarias;
    }
    public String getSucDireccion() {
        return this.sucDireccion;
    }
    
    public void setSucDireccion(String sucDireccion) {
        this.sucDireccion = sucDireccion;
    }
    public String getSucTelefono() {
        return this.sucTelefono;
    }
    
    public void setSucTelefono(String sucTelefono) {
        this.sucTelefono = sucTelefono;
    }




}


