package co.petsland.model;

// Generated 28/06/2015 09:53:51 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Veterinarias generated by hbm2java
 */
public class Veterinarias implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long vetCodigo;
	private String vetNombre;
	private String vetUsuCrea;
	private String vetUsuModifica;
	private String vetDireccion;
	private String vetTelefono;
	private String vetUrl;
	private String vetEstado;
	private Set<EventosVeterinarias> eventosVeterinariases = new HashSet<EventosVeterinarias>(
			0);
	private Set<VetsServs> vetsServses = new HashSet<VetsServs>(0);
	private Set<Sucursales> sucursaleses = new HashSet<Sucursales>(0);

	public Veterinarias() {
	}

	public Veterinarias(Long vetCodigo, String vetNombre, String vetUsuCrea,
			String vetDireccion, String vetTelefono, String vetEstado) {
		this.vetCodigo = vetCodigo;
		this.vetNombre = vetNombre;
		this.vetUsuCrea = vetUsuCrea;
		this.vetDireccion = vetDireccion;
		this.vetTelefono = vetTelefono;
		this.vetEstado = vetEstado;
	}

	public Veterinarias(Long vetCodigo, String vetNombre, String vetUsuCrea,
			String vetUsuModifica, String vetDireccion, String vetTelefono,
			String vetUrl, String vetEstado,
			Set<EventosVeterinarias> eventosVeterinariases,
			Set<VetsServs> vetsServses, Set<Sucursales> sucursaleses) {
		this.vetCodigo = vetCodigo;
		this.vetNombre = vetNombre;
		this.vetUsuCrea = vetUsuCrea;
		this.vetUsuModifica = vetUsuModifica;
		this.vetDireccion = vetDireccion;
		this.vetTelefono = vetTelefono;
		this.vetUrl = vetUrl;
		this.vetEstado = vetEstado;
		this.eventosVeterinariases = eventosVeterinariases;
		this.vetsServses = vetsServses;
		this.sucursaleses = sucursaleses;
	}

	public Long getVetCodigo() {
		return this.vetCodigo;
	}

	public void setVetCodigo(Long vetCodigo) {
		this.vetCodigo = vetCodigo;
	}

	public String getVetNombre() {
		return this.vetNombre;
	}

	public void setVetNombre(String vetNombre) {
		this.vetNombre = vetNombre;
	}

	public String getVetUsuCrea() {
		return this.vetUsuCrea;
	}

	public void setVetUsuCrea(String vetUsuCrea) {
		this.vetUsuCrea = vetUsuCrea;
	}

	public String getVetUsuModifica() {
		return this.vetUsuModifica;
	}

	public void setVetUsuModifica(String vetUsuModifica) {
		this.vetUsuModifica = vetUsuModifica;
	}

	public String getVetDireccion() {
		return this.vetDireccion;
	}

	public void setVetDireccion(String vetDireccion) {
		this.vetDireccion = vetDireccion;
	}

	public String getVetTelefono() {
		return this.vetTelefono;
	}

	public void setVetTelefono(String vetTelefono) {
		this.vetTelefono = vetTelefono;
	}

	public String getVetUrl() {
		return this.vetUrl;
	}

	public void setVetUrl(String vetUrl) {
		this.vetUrl = vetUrl;
	}

	public String getVetEstado() {
		return this.vetEstado;
	}

	public void setVetEstado(String vetEstado) {
		this.vetEstado = vetEstado;
	}

	public Set<EventosVeterinarias> getEventosVeterinariases() {
		return this.eventosVeterinariases;
	}

	public void setEventosVeterinariases(
			Set<EventosVeterinarias> eventosVeterinariases) {
		this.eventosVeterinariases = eventosVeterinariases;
	}

	public Set<VetsServs> getVetsServses() {
		return this.vetsServses;
	}

	public void setVetsServses(Set<VetsServs> vetsServses) {
		this.vetsServses = vetsServses;
	}

	public Set<Sucursales> getSucursaleses() {
		return this.sucursaleses;
	}

	public void setSucursaleses(Set<Sucursales> sucursaleses) {
		this.sucursaleses = sucursaleses;
	}

}
